#!/bin/bash

STARMADE_PATH='/home/steam/starmade/StarMade'

BLOCKCONFIG_PATH='customBlockConfig/BlockConfigImport.xml' # different name
BLOCKBEHAVIOR_PATH='data/config/'
FACTIONCONFIG_PATH='customFactionConfig/'
GAMECONFIG_PATH=''

cp BlockConfig.xml $STARMADE_PATH/$BLOCKCONFIG_PATH
cp blockBehaviorConfig.xml $STARMADE_PATH/$BLOCKBEHAVIOR_PATH
cp FactionConfig.xml $STARMADE_PATH/$FACTIONCONFIG_PATH
cp GameConfig.xml $STARMADE_PATH/$GAMECONFIG_PATH
cp StarMade-dedicated-server-linux.sh $STARMADE_PATH

cp server.cfg $STARMADE_PATH/

perl -pi -e 's/SUPER_ADMIN_PASSWORD\s?=.+/SUPER_ADMIN_PASSWORD = *REDACTED*/g' server.cfg
perl -pi -e 's/HOST_NAME_TO_ANNOUNCE_TO_SERVER_LIST\s?=.+/HOST_NAME_TO_ANNOUNCE_TO_SERVER_LIST = *REDACTED*/g' server.cfg

git add .
git commit -a -m "Updated"

git push origin master

cp $STARMADE_PATH/server.cfg .
